services:

  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: syntax_admin
      POSTGRES_DB: SyntaxDb
    ports:
      - 2345:5432
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2

  flyway:
    image: flyway/flyway
    entrypoint: ["bash"]
    command: -c sh /flyway/sql/migrate.sh
    volumes:
      - ./Migrations:/flyway/sql
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pg_data:
    driver: local
