CREATE DATABASE SyntaxDb;

CREATE TABLE IF NOT EXISTS public."Blobs"
(
    "Id" uuid NOT NULL,
    "Path" text COLLATE pg_catalog."default" NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "Timestamp" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT "PK_Blobs" PRIMARY KEY ("Id")
) TABLESPACE pg_default;

CREATE TABLE public."UserSettings" (
	"Id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "DisplayName" TEXT NOT NULL,
    "ShowTopics" BOOLEAN NOT NULL,
    "ShowComments" BOOLEAN NOT NULL,
    "ProfilePictureId" uuid,
	CONSTRAINT "FK_UserSettings_Blobs_ProfilePictureId" FOREIGN KEY ("ProfilePictureId") REFERENCES public."Blobs" ("Id"))
	TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."Roles"
(
    "Id" text COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(256) COLLATE pg_catalog."default",
    "NormalizedName" character varying(256) COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" text COLLATE pg_catalog."default" NOT NULL,
    "IsDeleted" boolean NOT NULL,
	"UserSettingsId" uuid NOT NULL,
    "JoinedDate" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "UserName" character varying(256) COLLATE pg_catalog."default",
    "NormalizedUserName" character varying(256) COLLATE pg_catalog."default",
    "Email" character varying(256) COLLATE pg_catalog."default",
    "NormalizedEmail" character varying(256) COLLATE pg_catalog."default",
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text COLLATE pg_catalog."default",
    "SecurityStamp" text COLLATE pg_catalog."default",
    "ConcurrencyStamp" text COLLATE pg_catalog."default",
    "PhoneNumber" text COLLATE pg_catalog."default",
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Users_UserSettings_Id" FOREIGN KEY ("UserSettingsId") REFERENCES public."UserSettings" ("Id")
) TABLESPACE pg_default;
	
CREATE INDEX IF NOT EXISTS "EmailIndex"
    ON public."Users" USING btree
    ("NormalizedEmail" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
	
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex"
    ON public."Users" USING btree
    ("NormalizedUserName" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"
    ON public."Roles" USING btree
    ("NormalizedName" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."UserRoles"
(
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "RoleId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES public."Roles" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_UserRoles_RoleId"
    ON public."UserRoles" USING btree
    ("RoleId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
	
CREATE TABLE IF NOT EXISTS public."UserClaims"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_UserClaims_UserId"
    ON public."UserClaims" USING btree
    ("UserId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."RoleClaims"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "RoleId" text COLLATE pg_catalog."default" NOT NULL,
    "ClaimType" text COLLATE pg_catalog."default",
    "ClaimValue" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId")
        REFERENCES public."Roles" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_RoleClaims_RoleId"
    ON public."RoleClaims" USING btree
    ("RoleId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."UserLogins"
(
    "LoginProvider" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "ProviderKey" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "ProviderDisplayName" text COLLATE pg_catalog."default",
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_UserLogins_UserId"
    ON public."UserLogins" USING btree
    ("UserId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."UserTokens"
(
    "UserId" text COLLATE pg_catalog."default" NOT NULL,
    "LoginProvider" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "Name" character varying(128) COLLATE pg_catalog."default" NOT NULL,
    "Value" text COLLATE pg_catalog."default",
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
) TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."Topics"
(
    "Id" uuid NOT NULL,
    "UserId" text COLLATE pg_catalog."default",
    "Title" character varying(80) COLLATE pg_catalog."default" NOT NULL,
    "Body" text COLLATE pg_catalog."default" NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "Timestamp" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT "PK_Topics" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Topics_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_Topics_UserId"
    ON public."Topics" USING btree
    ("UserId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public."Comments"
(
    "Id" uuid NOT NULL,
    "TopicId" uuid NOT NULL,
    "UserId" text COLLATE pg_catalog."default",
    "Content" text COLLATE pg_catalog."default" NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "Timestamp" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Topics_TopicId" FOREIGN KEY ("TopicId")
        REFERENCES public."Topics" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Comments_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES public."Users" ("Id") MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_Comments_TopicId"
    ON public."Comments" USING btree
    ("TopicId" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS "IX_Comments_UserId"
    ON public."Comments" USING btree
    ("UserId" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

GRANT ALL PRIVILEGES ON DATABASE SyntaxDb TO postgres;

CREATE ROLE syntax_admin WITH LOGIN PASSWORD 'syntax_admin';

GRANT CONNECT ON DATABASE SyntaxDb TO syntax_admin;
GRANT USAGE ON SCHEMA public TO syntax_admin;
GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA public TO syntax_admin;
