name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: 
        docker build -t mssql-image .

    - name: Run docker image
      run:
        docker run -d -p 1433:1433 --name syntax-mssql-server mssql-image
        
      env:
        SA_PASSWORD: "Pwd12345!"
        ACCEPT_EULA: 'Y'
    
    # Optional: Add a delay for SQL Server readiness
    - name: Wait for SQL Server to be ready
      run: sleep 120
    
    - name: Build the Test Project
      run: dotnet build Syntax.Tests/Syntax.Tests.csproj --configuration Release

    - name: Run tests
      run: dotnet test Syntax.Tests/Syntax.Tests.csproj --configuration Release --no-build
