name: Application tests
env:
  DB_DATABASE: syntax_tests
  DB_PASSWORD: "Pwd12345!"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: "Pwd12345!"
          ACCEPT_EULA: "Y"
        ports:
          - 1433:1433
        options: >-
          --health-cmd='[ "$(sqlcmd -S localhost -U SA -P ${{env.DB_PASSWORD}} -Q "SELECT 1" | wc -l)" -ge 1 ]'
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Test Project
      run: dotnet build Syntax.Tests/Syntax.Tests.csproj --configuration Release

    - name: Run tests
      run: dotnet test Syntax.Tests/Syntax.Tests.csproj --configuration Release --no-build
