name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start MSSQL Server
      run: docker run -d -p 1433:1433 --name syntax-mssql-server mcr.microsoft.com/mssql/server:2019-latest
